name: Format

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@master

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Format code
        run: pnpm format

      - name: Commit and push if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add .
            git commit -m "style: Auto-format via prettier"
            git push
          fi
