name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@master

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Lint
        run: pnpm lint
